name: generate-svg
on: 
  push:
    branches:
      - main
jobs:
  generate-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: create output dir
        run: mkdir build
      - uses: Timmy/plantuml-action@v1
        with:          
          args: "k8s-for-devs-simplified.plantuml -tsvg -o build"
      # - name: Upload svg file to artifacts
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: svg-file
      #     path: k8s-for-devs-simplified.svg
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build
          clean: false