name: generate-svg
on: [push]
jobs:
  generate-svg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lokkju/github-action-plantuml@master
        with:          
          args: "k8s-for-devs-simplified.plantuml -tsvg"
          PLANTUML_VERSION: "1.2021.10"
      - name: Upload svg file
        uses: actions/upload-artifact@v2
        with:
          name: svg-file
          path: k8s-for-devs-simplified.svg